-
  name: play 1
  hosts: server1
  tasks:
    - name: Execute a unix command
      command: uname -a
    - name: Install web packaage
      yum:
        name: httpd
        state: present
    - name: Start web server
      service:
        name: httpd
        state: started
      